# Arrow Image Classification

Used Dataset: Arrow Image Dataset (2018, Jaemin Lim, Hyeoni Nam)

Input: 128 x 128 Image 

Output: One-hotted Digit (6 labels: up, right, left, down, circle, cross)

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [0]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.preprocessing.image import ImageDataGenerator

In [0]:
np.random.seed(3)

In [11]:
train_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
                  'drive/My Drive/Colab Notebooks/Datasets/ArrowImages/train',
                  target_size=(128, 128),
                  batch_size=4,
                  class_mode='categorical')

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
                 'drive/My Drive/Colab Notebooks/Datasets/ArrowImages/test',
                 target_size=(128, 128),
                 batch_size=4,
                 class_mode='categorical')

Found 96 images belonging to 6 classes.
Found 24 images belonging to 6 classes.


In [0]:
model = Sequential()
model.add(Conv2D(8, kernel_size=(5, 5), activation='relu', input_shape=(128, 128, 3)))  # 128 * 128 -> 124 * 124
model.add(MaxPooling2D(pool_size=(2, 2)))  # 124 * 124 -> 62 * 62
model.add(Conv2D(16, kernel_size=(5, 5), activation='relu'))  # 62 * 62 -> 56 * 56
model.add(MaxPooling2D(pool_size=(2, 2)))  # 56 * 56 -> 28 * 28
model.add(Conv2D(32, kernel_size=(5, 5)))  # 28 * 28 -> 24 * 24
model.add(MaxPooling2D(pool_size=(2, 2)))  # 24 * 24 -> 12 * 12
model.add(Conv2D(64, kernel_size=(3, 3)))  # 12 * 12 -> 10 * 10
model.add(Flatten())
model.add(Dense(100, activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(6, activation='softmax'))

In [0]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [21]:
model.fit_generator(train_generator, steps_per_epoch=24, epochs=20, validation_data=test_generator, validation_steps=4)

Epoch 1/20
24/24 [==============================] - 0s 20ms/step - loss: 7.8145e-05 - acc: 1.0000 - val_loss: 1.1937 - val_acc: 0.8750
Epoch 2/20
24/24 [==============================] - 0s 19ms/step - loss: 7.3149e-05 - acc: 1.0000 - val_loss: 1.1929 - val_acc: 0.8750
Epoch 3/20
24/24 [==============================] - 0s 21ms/step - loss: 6.7792e-05 - acc: 1.0000 - val_loss: 1.1920 - val_acc: 0.8750
Epoch 4/20
24/24 [==============================] - 0s 19ms/step - loss: 6.3246e-05 - acc: 1.0000 - val_loss: 1.1914 - val_acc: 0.8750
Epoch 5/20
24/24 [==============================] - 0s 19ms/step - loss: 5.9088e-05 - acc: 1.0000 - val_loss: 1.1911 - val_acc: 0.8750
Epoch 6/20
24/24 [==============================] - 0s 19ms/step - loss: 5.5656e-05 - acc: 1.0000 - val_loss: 1.1905 - val_acc: 0.8750
Epoch 7/20
24/24 [==============================] - 0s 19ms/step - loss: 5.2235e-05 - acc: 1.0000 - val_loss: 1.1898 - val_acc: 0.8750
Epoch 8/20
24/24 [==============================] - 0s 

In [22]:
scores = model.evaluate_generator(test_generator, steps=4)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1] * 100))

acc: 87.50%


In [23]:
output = model.predict_generator(test_generator, steps=4)
np.set_printoptions(formatter={'float': lambda x: '{0:0.3f}'.format(x)})
print(test_generator.class_indices)
print(output)

{'circle': 0, 'cross': 1, 'down': 2, 'left': 3, 'right': 4, 'up': 5}
[[1.000 0.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 1.000 0.000 0.000]
 [0.000 0.000 0.002 0.985 0.013 0.000]
 [0.000 0.000 1.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.957 0.026 0.017]
 [0.000 0.000 0.014 0.055 0.932 0.000]
 [0.000 0.000 0.703 0.297 0.000 0.000]
 [1.000 0.000 0.000 0.000 0.000 0.000]
 [1.000 0.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.000 0.000 1.000]
 [0.000 0.000 1.000 0.000 0.000 0.000]
 [0.000 1.000 0.000 0.000 0.000 0.000]
 [0.000 1.000 0.000 0.000 0.000 0.000]
 [1.000 0.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.000 0.005 0.995]
 [0.000 0.025 0.744 0.161 0.070 0.000]]
